# Generated by Django 4.1.7 on 2023-03-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='unique',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='report',
            name='email',
        ),
        migrations.RemoveField(
            model_name='report',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='last_name',
        ),
        migrations.AddField(
            model_name='report',
            name='pdf',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
