# Generated by Django 4.1.7 on 2023-03-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_rename_unique_report_username_remove_report_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
